query GetAdvertisement($advertisement: String!) {
  getAdvertisement(advertisement: $advertisement) {
    id
    price
    images
    open
    seller {
      fullName
      phoneNo
    }  
    book {
      id
      bookName
      authorName
      description
      category {
        name
      }
    }
  }
  getUserRating
  userBoughtAdvertisement(advertisement: $advertisement)
}