query GetBuyerHistory {
  getBuyerHistory {
    id
    advertisement {
      id
      book {
        bookName
        authorName
      }
      seller {
        fullName
        phoneNo
      }
      price
    }
    price
    isFinal
  }
}