query GetSellerResponds {
  getSellerResponds {
    id
    advertisement {
      id
      book {
        bookName
        authorName
      }
      price
    }
    buyer {
      fullName
    }
    price
  }
}