query SearchAdvertisements($searchInput: AdvertisementSearchType!) {
  searchAdvertisements(searchInput: $searchInput) {
    id
    images
    book {
      authorName
      bookName
    }
    price
    }
}